name = "gym-site"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "gym"
database_id = "6edc4bb5-f374-4a85-8320-20b23f33b78e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gym"
