name = "gym-site"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "gym"
database_id = "4e8a5f45-b545-4e26-a69c-cdcf9c0c59a7"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gym"
